logging:
  level:
    ROOT: DEBUG
    com.java.spring: DEBUG

spring:
  application:
    name: Brand
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Brand
      username: rizwan
      password: Madina92
      auto-index-creation: false
      authentication-database: admin
  profiles:
    active: dev
server:
  port: 8081
  api:
   brand:
    url: http://localhost:8080/api/brands