version: '2'
services:
  brand-app:
    image: brand
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://brand-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=Brand
      - CONTAINER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  brand-mongodb:
    extends:
      file: mongodb.yml
      service: brand-mongodb
